In [32]:
import numpy as np

Q1. Pandas version

In [2]:
import pandas as pd

In [3]:
pd.__version__

'3.0.6'

Uploading the data

In [4]:
url = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'

In [5]:
df = pd.read_csv(url)

In [6]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

Q2 Records count:How many records are in the dataset?

In [8]:
df.shape

(10000, 11)

Q3 fuel_types: How many fuel types are presented in the dataset?

In [11]:
df['fuel_type'].nunique()

3

Q4. Missing values :How many columns in the dataset have missing values?

In [12]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Q5. Max fuel efficiency:What's the maximum fuel efficiency of cars from Asia?

In [14]:
df1=df[df['origin']=='Asia']

In [15]:
df1

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [19]:
df1['origin'].unique()

<StringArray>
['Asia']
Length: 1, dtype: str

In [20]:
df1['fuel_efficiency_mpg'].max()

np.float64(41.2)

Q6. Median value of horsepower

Find the median value of the horsepower column in the dataset.
Next, calculate the most frequent value of the same horsepower column.
Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
Now, calculate the median value of horsepower once again.

In [21]:
df['horsepower'].median()

np.float64(254.0)

In [22]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [23]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [24]:
df['horsepower'].median()

np.float64(252.0)

Q7. Sum of weights

Select all the cars from Asia
Select only columns vehicle_weight and model_year
Select the first 7 values
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [27]:
subset = df1[['vehicle_weight', 'model_year']]

In [28]:
subset7 = subset.head(7)

In [30]:
X = subset7.values

In [33]:
XTX = np.dot(X.T, X)

In [34]:
XTX_inv = np.linalg.inv(XTX)

In [35]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [36]:
temp = np.dot(XTX_inv, X.T)

In [37]:
w = np.dot(temp, y)

In [38]:
ans = w.sum()

In [39]:
ans

np.float64(0.36919696904925486)